# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CryptoMarket' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CryptoMarket
   pod 'RxSwift',    '~> 4.0'
   pod 'RxCocoa',    '~> 4.0'
   pod 'RxGesture'
   pod 'Alamofire'
   pod 'RxAlamofire'
   pod 'ObjectMapper'
   pod "SwiftChart"
   pod 'Charts'
   pod 'SwiftEntryKit'
   pod 'AlamofireImage'
   pod 'Comets'
   pod 'RAMAnimatedTabBarController'
   pod 'lottie-ios'

   plugin 'cocoapods-keys', {
   	  :project => "CryptoMarket",
  	  :target => "CryptoMarket",
  	  :keys => [
		    "MarketNewsAPIClient"    		    
  		    ]
		 }

   target 'CryptoMarketTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CryptoMarketUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
